### ISSUE TITLE
Lair Actions and Regional Effects lacking name causes "Undefined" for chat macros

### ISSUE THREAD

**Issue by mlenser** [mlenser/roll20-character-sheets#112]

**Comment by mlenser** [comment]
Fixed in 2.6.2

**Comment by symposion** [comment]
FWIW this only fixes the problem for new characters. I guess we need to manually edit the lair actions and regional effects to trigger an update to the macro?

**Comment by mlenser** [comment]
I can put in an updater in 3.1.1

**Comment by mlenser** [comment]
Done in 3.1.1
