### ISSUE TITLE
Output remaining spell slots when clicking on "spell slots" text

### ISSUE THREAD

**Issue by symposion** [mlenser/roll20-character-sheets#115]
Currently the text "Spell slots" underneath the list of spell slots is not clickable. It would be nice if this was clickable and it output a list of remaining spell slots - this could then be called as a macro and used by the Companion Script to output spell slot info after a spell has been cast.

**Comment by mlenser** [comment]
@symposion this is the same as https://github.com/mlenser/roll20-character-sheets/issues/108 right?

**Comment by symposion** [comment]
Not exactly, no. I envisioned this as purely a spell slots output:
1st Level: 2/4
2nd Level: 0/3
3rd Level: 1/2

or something like that. Ideally as compact as possible, so it could be output after e.g. spell casting to give people a clear picture of where they stood. Obviously doing #108 makes this less important, but it might still be useful in some situations.

**Comment by mlenser** [comment]
ah, I see. Ok. I'll add both. Btw you got your passive skills.

**Comment by mlenser** [comment]
Please checkout the new spells chat macro and verify that this is still needed. I think so because you don't want to list the spells themselves. I can create a simple macro if so.

**Comment by symposion** [comment]
Hey Mark,

Like the new spellbook output! Ideally I'd still like this feature at some point, because I'd like to do some more fancy stuff with the script at some point in the future, but it's a low priority and I'm some way off having the time to do anything useful with it. Spending most of my time building a PV installation at the moment!

Lucian

**Comment by mlenser** [comment]
So do you still want this done for script purposes?

**Comment by symposion** [comment]
Ideally, yes, but as I said, it's going to be a while before I'm going to get round to making use of it, so if it's hassle then don't worry about it.

**Comment by mlenser** [comment]
So just remove the spells from what I have now, ya?

**Comment by symposion** [comment]
Yep.

**Comment by mlenser** [comment]
This is done as of 4.0.2
