### ISSUE TITLE
Legendary cost support

### ISSUE THREAD

**Issue by symposion** [mlenser/roll20-character-sheets#121]
Currently the sheet doesn't parse out the legendary action points value either from the SRD or script import. It also doesn't parse out the costs on individual actions where they are more than one "(costs 2 actions)" - and there isn't actually a place for this value to go.

Ideally at some point legendary points would be able to auto-decrement with script support the way ammo does at the moment.

**Comment by symposion** [comment]
Hmmm. Looking at the sheet worker code, it *should* be getting the overall action count. But for some reason it isn't. I tested with an Ancient Black Dragon from the SRD.

**Comment by symposion** [comment]
Ok I've fixed the count parsing and sent you a PR: https://github.com/mlenser/roll20-character-sheets/pull/123 The other stuff is more of an enhancement request I guess.

**Comment by mlenser** [comment]
Closed as part of my new issue tracker via bitbucket
