### ISSUE TITLE
Repeated Compendium NPC drop doesn't work well

### ISSUE THREAD

**Issue by symposion** [mlenser/roll20-character-sheets#124]
If you drop an NPC onto a character sheet, and then drop another, different one on later, it doesn't really work - only part of the new NPC gets imported and you end up with a mishmash of the old and the new. I have no idea if this is something you can fix credibly, so feel free to close this, but I *thought* I'd seen this work better in the past, so I've opened this in case there's a regression somewhere.

**Comment by mlenser** [comment]
It cannot be fixed. It requires all fields being cleared which sheet workers can't do.
