### ISSUE TITLE
Crit damage calculation doesn't work for spells

### ISSUE THREAD

**Issue by joesinghaus** [mlenser/roll20-character-sheets#127]
**Bug**: when calculating the additional crit damage on a spell attack, both the regular damage and the damage in the crit field are added together.

**Expected**: only the damage in the crit field is used to calculate the extra critical damage.

**Comment by mlenser** [comment]
That is not a bug, it is the previous intended behavior that prevented hundreds of users from leaving crit blank like they did on on old versions.

However see https://app.roll20.net/forum/permalink/3363514/ which already changes this behavior to only be the crit field (which is populated by the damage field via sheet workers if the crit field is empty)

**Comment by joesinghaus** [comment]
Mark, this is on 3.2.2, where it works correctly for attacks and doesn't for spells. Screenshot attached; unless I'm completely off here, this cannot be intended behaviour.
<img width="294" alt="screen shot 2016-05-13 at 19 58 39" src="https://cloud.githubusercontent.com/assets/18185704/15257127/2a2237a4-1945-11e6-8153-2962d8960023.png">

**Comment by mlenser** [comment]
See 3.2.4 https://app.roll20.net/forum/permalink/3372684/

If you send the version number and screenshot earlier it'll be easier for me to understand. :)

Thanks for pointing it out!

**Comment by joesinghaus** [comment]
I'll try to improve my bug-reporting skills :). Thanks for the fix!
