### ISSUE TITLE
Add full translations for German

### ISSUE THREAD

**Issue by mlenser** [mlenser/roll20-character-sheets#132]

**Comment by mlenser** [comment]
@Rouby & @svenbeyer13 there are some missing translations for German. Sheet version 4.0.0 will go live on Tuesday with the new translation system (built into roll20). If you want these on there it would be best to get them in before then. Otherwise we'll have to wait a week.

Let me know if I can be of any assistance. Here is the list that is missing:
All class features. They are nice to have, otherwise they're in english, but this is a large amount of work so understandable if this doesn't get done.

ABILITY_CHECKS_QUERY
ABILITY_SCORES
ACID
ADD_HALF_PROFICIENCY_TO_UNPROFICIENT_SAVING_THROWS
AMMO_AUTO_USE
AUTO_REVERT_ADV
BIG
BLUDGEONING
BREAK_TIES
CANCEL
CLASS_FEATURES_TITLE
COLD
COLOR
CONDENSE
CRIT_ATTACHER_TOOLTIP
CRIT_DAMAGE_TOOLTIP
DISPLAY_TEXT
EVERY
FIELD
FILTERS
FIRE
FORCE
HEAL_FOR
HIDE_NPC_INFO_ATTACK
HIDE_NPC_INFO_DAMAGE
HOUSERULES
IMPORT
LBS
LEVELS
LIGHTNING
LONG_REST
MISCELLANEOUS
MULTIPLIER
NECROTIC
PIERCING
POINTS_OF_ORIGIN
POISON
PSYCHIC
RADIANT
REGIONAL_EFFECTS
REQUIRES_API
RESTS
ROLL_2
ROLL_OPTIONS
ROLL_TEMPLATE
SAVE_FAILURE
SAVE_SUCCESS
SAVING_THROWS_QUERY
SHORT_REST
SHOW_PASSIVE
SHOW_RESTS
SHOW_SPELL_LEVEL_IF_ALL_SLOTS_ARE_USED
SHOW_TOTALS
SHOW_UNPREPARED_SPELLS
SLASHING
SPECIAL_EFFECTS
SPELLCASTING_LEVEL
STATBLOCK
TEXT_SIZE
THUNDER
TRACKER
TRAITS
TURN_OFF_FILTERING
USED
USES
VS
VS_FIEND_OR_UNDEAD

**Comment by mlenser** [comment]
Added
"1_ACTION": "1 action",
  "1_BONUS_ACTION": "1 bonus action",
  "1_REACTION": "1 reaction",
  "1_MINUTE": "1 minutes",
  "10_MINUTES": "10 minutes",
  "1_HOUR": "1 hour",
  "8_HOURS": "8 hours",
  "12_HOURS": "12 hours",
  "24_HOURS": "24 hours",
  "7_DAYS": "7 days",
  "10_DAYS": "10 days",
  "30_DAYS": "30 days",
  "INSTANTANEOUS": "Instantaneous",
  "UNTIL_DISPELLED": "Until dispelled",
  "UNTIL_DISPELLED_OR_TRIGGERED": "Until dispelled or triggered",
  "UP_TO_1_MINUTE": "up to 1 minute",
  "1_ROUND": "1 round",
  "UP_TO_1_ROUND": "up to 1 round",
  "UP_TO_6_ROUNDS": "up to 6 rounds",
  "UP_TO_10_MINUTES": "up to 10 minute",
  "UP_TO_1_HOUR": "up to 1 hour",
  "UP_TO_2_HOURS": "up to 2 hours",
  "UP_TO_8_HOURS": "up to 8 hours",
  "UP_TO_12_HOURS": "up to 12 hours",
  "UP_TO_24_HOURS": "up to 24 hours",
  "INSTANTANEOUS_OR_1_HOUR": "Instantaneous or 1 hour",
  "SPECIAL": "Special",
  "HALF_DAMAGE": "half damage",
  "OR": "or",
  "IF_THE_TARGET_IS": "If the target is",
  "ARROWS": "Arrows",
  "BITE": "Bite",
  "DRAGON": "Dragon",
  "LAWFUL_EVIL": "lawful evil",
  "ONE_CREATURE": "one creature",
  "AMPHIBIOUS": "Amphibious"

**Comment by mlenser** [comment]
This should be the last batch:

"CLASS_AND_LEVEL_PLACEHOLDER": "Generated after adding a class on the \"Character\" tab",
"DEATH_SAVING_THROW": "Death saving throw",
"DEATH_SAVING_THROWS": "Death saving throws",
"HIT_POINTS_TEMPORARY": "Temporary hit points",
"ABILITY_CHECK": "Ability check",
"PASSIVE_ABILITY_CHECK": "Passive ability check",
"COPPER_PIECES": "Copper pieces",
"SILVER_PIECES": "Silver pieces",
"ELECTRUM_PIECES": "Electrum pieces",
"GOLD_PIECES": "Gold pieces",
"PLATINUM_PIECES": "Platinum pieces",
"TOTAL_GOLD_VALUE": "Total gold value",
"HIT_POINTS_ROLLED": "Hit points rolled",
"AS": "as"

**Comment by yorickdowne** [comment]
Which of these are still outstanding?

**Comment by mlenser** [comment]
All and more. English gets put in for any missing values so you can find any English and replace it.
