### ISSUE TITLE
Adult White Dragon actions have the wrong damage

### ISSUE THREAD

**Issue by yorickdowne** [mlenser/roll20-character-sheets#138]
When importing an Adult White Dragon from SRD or JSON, the damage for its actions is just its strength bonus, without any damage dice.

Tested in 3.6.1 and 4.1.0. 4.1.0 is arguably worse, as it imports the saving throw for the breath as Str instead of Con.

**Comment by mlenser** [comment]
This seems to be true for all creatures. Tested on adult black dragon as well.

**Comment by mlenser** [comment]
If you pull the latest this should be fixed. I'll run some more tests and release a version soon.

**Comment by mlenser** [comment]
Should be fixed.
