### ISSUE TITLE
Adult White Dragon breath weapon has the wrong savings throw

### ISSUE THREAD

**Issue by yorickdowne** [mlenser/roll20-character-sheets#139]
When importing an Adult White Dragon into the 4.1.1 or 4.1.2 sheet, its Cold Breath action imports with a Strength saving throw. It should be Constitution.
This happens when importing from JSON or SRD.

**Comment by mlenser** [comment]
I'll verify (in bed now)

I checked the ability score used for damage, but not for saving throws to calculate DC or the ability to roll to save.

**Comment by yorickdowne** [comment]
Do you have an update or ETA? I will ask my GMs to look out for this for now and to work around it when prepping their games.

**Comment by mlenser** [comment]
It'll be fixed for Pro users within a few hours. Non-pro early next week - likely Tuesday.

**Comment by mlenser** [comment]
Fixed via 4.1.3
