### ISSUE TITLE
D&D 5e Shaped Character Sheet bugs

### ISSUE THREAD

**Issue by CGTNathan** [mlenser/roll20-character-sheets#144]
During my games, I've come across 6 bugs that really get in the way of gameplay. I prefer to open Character sheets as a separate window because it is more convenient. A lot of these bugs still happen when popped out, but the majority is when it is in a separate window. I will post screenshots as I take them.

1. Leveling up PCs - For some odd reason, when I level them up, it doesn't actually work. The sheet has no change. I have to leave and come back multiple times for the XP and Spell Slots to update, and then the next time I come it will be back at level 2 instead of level 3. I tried changing it in the attributes area as well, but that still did not work. WORKING FOR NOW
2. Advantage/Disadvantage - Today we encountered a weird bug where it wouldn't roll adv., or showed the adv. symbol on a regular roll. It was very confusing. WORKING FOR NOW
3. Saving throws - When making Features and Traits with saving throws, they would be removed right after I wrote them. They used to work just fine. WORKING FOR NOW
4. Weight - After putting in values of weight, it gave the wrong number and didn't update the actual weight the character was holding. After leaving and coming back multiple times it began to work, but broke when we added another item.  http://image.prntscr.com/image/54018c60a374427286a900a0c473fd1b.png WORKING FOR NOW
5. Spells - The spell filter has been acting very strangely. It's counting Cantrips as 1st level, then not counting them at all. It's not showing prepared, it's not organizing them by level of spell. Spell making is also very tedious because when I type something into Duration or Material, it automatically deletes what I wrote. WORKING FOR NOW

**Comment by CGTNathan** [comment]
Currently everything is working fine, but when I play with other people these bugs randomly appear.

**Comment by mlenser** [comment]
If they are only breaking when other players are around please confirm that and reopen the issue for those that still exist.

My game acts a bit weird when other players are around, but I can't consistently reproduce it. If that is the case it's likely a roll20 bug that we need them to fix. But to do that we need a solid reproduction path.

**Comment by CGTNathan** [comment]
Weight and Spells are acting up again.

**Comment by mlenser** [comment]
Please provide reproduction steps on a new character or send me an invite and give me access to edit the character where the issue can be reproduced consistently.
