### ISSUE TITLE
Melee/Ranged weapons should not default to strength/dex more than once

### ISSUE THREAD

**Issue by joesinghaus** [mlenser/roll20-character-sheets#146]
This might be controversial, but I think that melee/ranged attacks/features should not default to strength resp. dexterity more than once. Reason: due to the bug with empty values and defaults that roll20 won't fix, it means that you *cannot* change the attributes to none for these attacks.
This not only causes problems for two-weapon fighting without the fighting style (where you do not add the attribute modifier to damage), it also breaks Divine Smite damage as long as Divine Smite is of type melee.

**Comment by mlenser** [comment]
It's only supposed to set it once. That is the issue. Fixing that should solve the not being able to switch issue. Though divine smite and improved divine smite should be labeled as other, not melee.

**Comment by mlenser** [comment]
Fixed in 6.0.0
