### ISSUE TITLE
Spellcasting bonus and penalties

### ISSUE THREAD

**Issue by kiddoc73** [mlenser/roll20-character-sheets#149]
If there is any + sign in front of the bonus for spell attack, damage or DC, the output for a spell is always 0. The math is there if you hover, but only 0 shows. if you only place the digit (i.e. 2) then the math works. 

![image](https://cloud.githubusercontent.com/assets/20718186/17239122/39891942-5527-11e6-8822-6774e35b4dd8.png)

![image](https://cloud.githubusercontent.com/assets/20718186/17239095/13e9ca38-5527-11e6-8e2a-59659582ddad.png)

**Comment by mlenser** [comment]
Don't put a + then. :P

**Comment by kiddoc73** [comment]
Just letting you know :+1:  :)

**Comment by mlenser** [comment]
I don't think there is any way to fix it besides stripping out a leading + sign
