### ISSUE TITLE
French translation <sup> tag not working on spell levels

### ISSUE THREAD

**Issue by Orta15a** [mlenser/roll20-character-sheets#157]
As the title says, the <sup> and </sup> tags are not correctly parsed and thus not puting the text in superscript position, in the spell level description.

I suggest remove the <sup> tag and replace "e" by "er" and "ème". @Alzam01

**Comment by mlenser** [comment]
@Alzam01 can you look at this?

**Comment by Alzam01** [comment]
Done :)

For the record, <*sup> tag seems to work on the sheet, but not on spell display. It's correctly displaying while in edit mode for spells.

![2016-09-08 17_22_18](https://cloud.githubusercontent.com/assets/14132657/18355266/ded2378a-75e8-11e6-9e5e-88e351d65ac6.png)
![2016-09-08 17_21_57](https://cloud.githubusercontent.com/assets/14132657/18355259/dbea2410-75e8-11e6-9817-59c60c9856ef.png) ![2016-09-08 17_24_19](https://cloud.githubusercontent.com/assets/14132657/18355354/20c8a8ea-75e9-11e6-87d8-35f9ee5b1158.png)

**Comment by Orta15a** [comment]
Thanks ! Let me take the opportunity to thank you both, for the amazing sheet, and the always on point french translation :). Keep up the good work, and I'll continue reporting issues if I found some.
