### ISSUE TITLE
Translation not done on Shaped ability check macro

### ISSUE THREAD

**Issue by Orta15a** [mlenser/roll20-character-sheets#159]
Hi,

I am not sure if this is an issue of the sheet or the Companion script, but when using 

**%{Loktar-Varzlog|shaped_ability_checks}**, I have the Skills in French and the Characteristics in English.

To compare with **%{Loktar-Varzlog|shaped_saving_throw}** where the Characteristics are in French.

![bugr20](https://cloud.githubusercontent.com/assets/6920836/18356936/8346949e-75b4-11e6-82d1-94fe13aaddd1.PNG)

**Comment by mlenser** [comment]
This will be fixed in 6.1.2.

Please let me know if it isn't - I have no way to verify.

**Comment by Orta15a** [comment]
Updated to 6.1.2., and can confirm this is fixed. I had to fiddle a little with the sheet option page (Click and unclick See total on the Macro part), for the fix to work. Thanks !

**Comment by mlenser** [comment]
Cool!
