### ISSUE TITLE
Skill translation

### ISSUE THREAD

**Issue by Netoen** [mlenser/roll20-character-sheets#166]
I've translated fields in the file, and most of them do work - except for skill names. Am I missing something ?

**Comment by mlenser** [comment]
Sorry, what? The skills should all be translated. Did you add custom ones?

**Comment by Netoen** [comment]
Nope. Right inside copied ru.json I edited values for things like "ACROBATICS" and etc. and it had no effect inside sheet in game. Here's my contents: 
[RUS.txt](https://github.com/mlenser/roll20-character-sheets/files/598107/RUS.txt)

**Comment by mlenser** [comment]
If you'd like to maintain the russian translations I'd appreciate it: https://github.com/mlenser/roll20-character-sheets/blob/master/5eShaped/translations/ru.json

You need to put the translations into the sheet editor alongside the html and css.

**Comment by Netoen** [comment]
First of all, thank you for replying and trying to help out.
Yes, I did it. As I said above - a lot of things in sheet got indeed translated: 
http://imgur.com/rxb04Tc
But ... not skills in particular O-o

**Comment by mlenser** [comment]
If you've updated a lot of missing translations can you send me a Pull Request?

Skills come from Sheet Workers and perhaps may not update until roll20 integrates the changes (which has to go through me pushing to them)

**Comment by Netoen** [comment]
I've just tried copying whole en.json and editing "ACROBATICS"'s value in it - again, no luck.
I've tried to copy whole thing over to dev servers - again, no difference.
As per pull request - yes, I understand that original ru.json I used as template is pretty outdated and needs some fixes to it, which I will figure out in some time - and then make a proper Pull. Allthough if you would insist - I can do it right now, though I am not very much acquainted with how GitHub works.
If there's anything else you want of me, some tests or logs - feel free to ask.

**Comment by mlenser** [comment]
I think you may have misunderstood what I wrote above. The skills come from sheetworkers which pulls the data from roll20. Until I push my code to roll20 it will not be up to date. There is absolutely nothing you can do manually to make it work until I do so.

If your text file is up to date then I could use that. Up to you.

The earliest I'll push the code is next Tuesday, but I'm not certain that I will. I'm trying to get it ready in time, but we'll see.
