### ISSUE TITLE
Feature request: marks on overencumberence and H.overencumberence

### ISSUE THREAD

**Issue by Netoen** [mlenser/roll20-character-sheets#167]
Just like sheet companion script is capable of placing green/red dots over token in case of (dis)advantage to track it - I propose some other icons being placed when character go over critical encumberence values. 
Of course imho it should be toggleable, like ammo usage in settings.

**Comment by mlenser** [comment]
This would be a feature for Lucian's script. That can affect the token. The sheet can't.

**Comment by Netoen** [comment]
Should I post this request somewhere else ? I presume it's Lucian who maintain shaped sheet's companion script ? And yeah, I understand that sheet itself can't do such things. I meant the option for toggling could be in sheet's settings.

**Comment by mlenser** [comment]
Sheet settings are only for things that impact the sheet. Ammo for example reduces ammo by 1 in the roll template so it has to have a sheet setting.

There are a myriad of script settings that don't have a sheet setting and this would be one of them.
It seems Lucian has an issue for this https://github.com/symposion/roll20-shaped-scripts/issues/257
