### ISSUE TITLE
[Reshaped] Cannot delete last armor

### ISSUE THREAD

**Issue by Rouby** [mlenser/roll20-character-sheets#54]
Steps to reproduce:
 - create a new character-handout
 - go to equipment-tab
 - add armor
 - try to delete armor

**Comment by Rouby** [comment]
btw great work! I just discovered your new sheet today and am already in love :+1:

**Comment by mlenser** [comment]
I see the same issue. I'll try to debug it later. Didn't solve it immediately as it's not blocking.

And thanks for the positive feedback and helping with translations again! :)

**Comment by Rouby** [comment]
This issue seems to be fixed in 2.2.2, but it persists for equipment (and possible others)

**Comment by mlenser** [comment]
https://app.roll20.net/forum/post/3081131/cannot-delete-unedited-repeating-item roll20 bug for deleting items.

Until that is fixed I won't try to address it specifically for my sheet as it's likely a roll20 bug.

**Comment by mlenser** [comment]
This looks fixed on the latest. Let me know if otherwise.
