### ISSUE TITLE
Initiative without clicking token?

### ISSUE THREAD

**Issue by bushong1** [mlenser/roll20-character-sheets#58]
Is there any way to assign initiative without clicking a token? I'm guessing this is a limitation of roll20, but I figured I'd ask. I'm running 5e's Out of the Abyss and its getting really tedious to roll initiative for 10 npc's plus track pcs.

**Comment by mlenser** [comment]
You can change this setting on the setting tab (cog wheel) of the character sheet.

For my usage it's easier to create a token action which references the initiative and then I can easily add creatures to the turn order. Having them on the turn order is much easier than trying to keep track off them off it.

But you're welcome to do it however works best for you.

**Comment by Rouby** [comment]
[GroupInitiative](https://app.roll20.net/forum/post/1066916/script-groupinitiative-roll-initiative-for-a-group-of-tokens-take-the-lowest-value-and-add-them-to-the-turn-order) - If you are a Pro-Users you could try that script, lets you select a group of tokens and roll initiative for all of them at once.

**Comment by bushong1** [comment]
Thanks guys, @mlenser's suggestion of creating a macro for token actions seems to be what I'm looking for.  Not a pro user, so no option there.  Still seems rather clunky, but I'll take it.
