### ISSUE TITLE
[Reshaped] Remove scrollbar from Features & Traits / Equipment

### ISSUE THREAD

**Issue by Rouby** [mlenser/roll20-character-sheets#59]
I feel like its better to not have a scrollbar for Features & Traits / Equipment. I think it is easier to overlook ones abilities if you dont have to scroll inside this tiny frame. I have put all racial, class, and background features (and talents) there for my players and I have a better overview if I dont have to scroll there.

Maybe move Resistances & Immunities and Exhaustion above them if that is a concern?

What do you think?

**Comment by mlenser** [comment]
Scrollbars were introduced as a result of discussions on the forums. The problem with letting equipment and traits expand to infinity is that they can make the sheet very long. The idea is to bind them to a certain height so the sheet remains viewable and each area can be scrollable.

Features & Traits will be expanding to include things like Sneak Attack, Divine Smite, etc in the future so it shouldn't be at the bottom.

The best place to discuss this w/ the community is on the forums.

**Comment by Rouby** [comment]
Ok, I guess that makes sense. I will resort to change the CSS myself then ;)

I take a look at the forums for future issues first, although I wish discussion would move over here ;) I feel like Roll20s forums are too messy / unorganized for this kind.

**Comment by mlenser** [comment]
Ya, you can always use custom css (no guarantees that things won't change in the future though).

Github would definitely be nice. Perhaps I should start giving priority to github issues to encourage people to use it.
