### ISSUE TITLE
Repeating section for custom features

### ISSUE THREAD

**Issue by kkragenbrink** [mlenser/roll20-character-sheets#72]
This would be for things like "Tinkerer" or "Ear to the Ground" that aren't resource-driven, aren't class features, but should be on the sheet somewhere prominent.

**Comment by mlenser** [comment]
Those kind of features really belong in "Features & Traits" unless I am missing a use case.

**Comment by kkragenbrink** [comment]
Well right now you have a big red note saying "This section is going away" so I assumed that was going away. :)  Also, it would be nice to be able to put them in a repeating section that's clickable so that they create a lovely card in the chat when you try to share.  I think big open sections like the Features & Traits should be rare.

**Comment by mlenser** [comment]
Features & Traits will persist in the repeating form, not in the textarea form.

**Comment by kkragenbrink** [comment]
..wow I hadn't even noticed the addition of Edit Mode. Everything makes sense, now.  Awesome job.

**Comment by mlenser** [comment]
haha. :D

**Comment by kkragenbrink** [comment]
Oh, you know what though, it might be nice if those collapsed down to just the name like the other sections do so you have to click to see the full text. Just a thought.

**Comment by mlenser** [comment]
You can choose to put whatever you want there with "Display Text". Freetext will show in the roll template.

**Comment by kkragenbrink** [comment]
Yeah, yeah, looks really good.  Thanks for all the hard work on these.
