### ISSUE TITLE
[Reshaped] Provide visual feedback for prepared spells

### ISSUE THREAD

**Issue by Rouby** [mlenser/roll20-character-sheets#73]
Would it be possible to highlight prepared spells if the filter is selected instead of hiding un-prepared?

Or gray-out the not-prepared (opacity 70% or something).

I think this would be more usability-friendly, because spells remain in their positions and you dont loose oversight of your learned spells (especially useful for wizards).

**Comment by mlenser** [comment]
The goal of filtering is to hide everything that isn't currently being filtered for.

The only issue is the way it's laid out (2 columns) means that the item is just hidden, not removed from the DOM so you get some blank lines, but that shouldn't be an issue especially now that you'll only see the gray bar for spells when in presentation mode (when you'd be filtering).

**Comment by Rouby** [comment]
The use-case I'm looking at is switchting prepared and not-prepared spells after a long rest.

Would it be ok / possible to include a checkbox when in edit-mode to quickly change prepared-state of spells without opening the settings?

**Comment by mlenser** [comment]
Switching which spells are prepared is something a user will do uncommonly. They'll do it more than most other adjustments under the spell details, but not really enough to assume that all users would want it to be prevalent.

If a user leaves all spells toggled to show details and then turns off edit mode they can then adjust prepared state fairly quickly if they turn on edit more.

**Comment by Rouby** [comment]
But the spells-list can get pretty clusted if you are a higher level.

Consider the cleric who knows every spell which he has slots for; granted you dont need to add them all, but after some time the list gets pretty long.

A wizard can potentially know even more spells.

But you are probably right in that this is not a common task. I will wait for further feedback from my cleric and wizard players ;)

**Comment by Rouby** [comment]
I will close this issue, as it seems not to be a common use-case.
