### ISSUE TITLE
Ability check mod not set on character creation

### ISSUE THREAD

**Issue by Alzam01** [mlenser/roll20-character-sheets#83]
Ability check mod is not set on character creation, resulting in a blank after the "=". I think I know how to fix that, but not sure so I'm gonna leave it to you.
![2016-03-25 00_08_02](https://cloud.githubusercontent.com/assets/14132657/14033820/bbb852d8-f21d-11e5-9081-c08627378ded.png)

**Comment by mlenser** [comment]
Solved in next build
