### ISSUE TITLE
[Reshaped] Roll damage seperated from attack

### ISSUE THREAD

**Issue by Rouby** [mlenser/roll20-character-sheets#88]
Would it be feasible to add an option to roll the damage separated from attacks / spells?

I think the OGL Sheet from Roll20 does this if I remember correctly. After the attack you can click on an API-Button (inside the attack template) which rolls the damage.

The use case I'm looking at is, some feats / traits allow you to reroll either the attack or modify the damage.

E.g. Channel Divinity: Destructive Wrath

"When you roll lightning or thunder damage, you can use your Channel Divinity to deal maximum damage, instead of rolling."

Right now a player has to decide to use this feature before clicking the attack button, otherwise he could "meta-game" and first look at the rolled damage, and if it is high enough don't use the feature.

Sure there are ways around this (just force him to declare before attacking / or reroll all dice), but I think it would add value to the sheet to provide this method. And often times a player just decides after (s)he declared the attack (and already rolled) whether to use this feature or not.

**Comment by mlenser** [comment]
This was a purposeful choice when I first created the sheet - there was no desire to have a separate roll template for damage.
I see the use case, but it would require all damage rolls to require a second step of clicking damage just to meet this one case. That second step slowing down the game was the reason people cited for not wanting this feature. I think that cost is too high for most users so designing this feature for a very small subset of users is less than ideal. It would complicate things greatly.

Deciding whether to use the feature before the button is clicked is the best. The only time it would make a difference is crit fishing, but most lightning/thunder are saves.

**Comment by Rouby** [comment]
Alright, I thought that might be difficult to implement (and maybe too much hassle ;) ).
