### ISSUE TITLE
Non-damaging actions import with damage checkbox ticked

### ISSUE THREAD

**Issue by joesinghaus** [mlenser/roll20-character-sheets#96]
When a creature's actions are imported, actions that do no damage import with the damage checkbox ticked, doing 0+Str damage. Example: Thug's Multiattack, Lich's Cantrip Legendary Action. Lich's Frightening Gaze.

**Comment by mlenser** [comment]
![example](https://s3.amazonaws.com/files.d20.io/images/18282720/p7F0EjtjuMVtxRZGZHDRVw/med.JPG?1461057379)

**Comment by mlenser** [comment]
Fixed via 3.3.3
